document.writeln("<div id=\'header_wrap\' class=\'outer\'>");
document.writeln("        <header class=\'inner\'>");
document.writeln("          <a id=\'forkme_banner\' href=\'https://github.com/102306071/JapanOsakaTrip\'>View on Google Map</a>");
document.writeln("");
document.writeln("          <h1 id=\'project_title\'><a href=\'index.html\'></a>Japan Osaka Trip</h1>");
document.writeln("          <nav class=\'navbar navbar-inverse\'>");
document.writeln("            <div class=\'container-fluid\'>");
document.writeln("              <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("              <div class=\'navbar-header\'>");
document.writeln("                <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("                  <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                  <span class=\'icon-bar\'></span>");
document.writeln("                  <span class=\'icon-bar\'></span>");
document.writeln("                  <span class=\'icon-bar\'></span>");
document.writeln("                </button>");
document.writeln("              </div>");
document.writeln("");
document.writeln("              <!-- Collect the nav links, forms, and other content for toggling -->");
document.writeln("              <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("                <ul class=\'nav navbar-nav\'>");
document.writeln("                  <li><a href=\'makeup.html\'>化妝品</a></li>");
document.writeln("                  <li><a href=\'yodobashi.html\'>Yodobashi</a></li>");
document.writeln("                  <li><a href=\'usj.html\'>環球影城</a></li>            ");
document.writeln("                </ul>");
document.writeln("              </div><!-- /.navbar-collapse -->");
document.writeln("            </div><!-- /.container-fluid -->");
document.writeln("          </nav>");
document.writeln("        </header>");
document.writeln("    </div>");
document.writeln("");