document.writeln("    <div id=\'header_wrap\' class=\'outer\'>");
document.writeln("        <header class=\'inner\'>");
document.writeln("          <a id=\'forkme_banner\' href=\'https://github.com/102306071/JapanOsakaTrip\'>View on Google Map</a>");
document.writeln("");
document.writeln("          <a href=\'index.html\'><h1 id=\'project_title\'>Japan Osaka Trip</h1></a> ");
document.writeln("              <div class=\'container\'>");
document.writeln("                <!-- 一般用的網站選單列 -->");
document.writeln("                <div id=\'navbar\' class=\'navbar-inverse \'>");
document.writeln("                  <ul class=\'nav navbar-nav\'>");
document.writeln("                      <li><a href=\'#news\'>化妝品</a></li>");
document.writeln("                      <li><a href=\'#activities\'>Yodobashi</a></li>");
document.writeln("                      <li><a href=\'\'>環球影城</a></li>");
document.writeln("<!--                       <li><a href=\'#reports\'>專欄報導</a></li>");
document.writeln("                      <li><a href=\'#competitions\'>企業競賽</a></li> -->");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("                <!-- 一般用的網站選單列 -->");
document.writeln("");
document.writeln("              </div>");
document.writeln("");
document.writeln("        </header>");
document.writeln("    </div>");